---
name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['*']
    paths-ignore: ['docs/**']

  push:
    branches: ['*']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # Consider using pre-commit.ci for open source project
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  # With no caching at all the entire ci process takes 4m 30s to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build the Stack
        run: docker compose -f local.yml build

      - name: Run DB Migrations
        run: docker compose -f local.yml run --rm django python manage.py migrate

      - name: Run Django Tests
        run: docker compose -f local.yml run django pytest

      - name: Store coverage for badge
        if: ${{ runner.os == 'Linux' }}
        run: docker compose -f local.yml run django python print-coverage.py >> $GITHUB_ENV

      - name: Create coverage badge
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'spousesupportgroup/postthis' && github.event_name == 'push' && runner.os == 'Linux' }}
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0a3c8a2a341a5faf43c6cf3fe0bafbe1
          filename: spousesupportgroup-postthis-coverage.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          color: ${{ env.COVERAGE_COLOR }}

      - name: Tear down the Stack
        run: docker compose -f local.yml down
