---
name: Delete old container images

on:
  schedule:
    - cron: '3 23 * * *'

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'postthis'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'false'
          ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'
